### ISSUE TITLE
Can't see description if title of news doesn't fit in two lines

### ISSUE THREAD

**Issue by Dekedro** [vycius/NMAkademija#33]
Can't see description if title of news doesn't fit in two lines.

Tested on Android 4.4.4

![screenshot_2016-09-04-21-27-24 1](https://cloud.githubusercontent.com/assets/18313444/18233072/6ced5802-72e6-11e6-9893-eb5b3cf6f441.png)

**Comment by gediminasel** [comment]
This article didn't have description. :)

**Comment by Dekedro** [comment]
Still, if title takes more than two lines, it looks bad.

![screenshot_2016-09-05-17-59-35 1](https://cloud.githubusercontent.com/assets/18313444/18251975/1a7e8ba4-7395-11e6-844d-36c9429be18a.png)

I think that 'android:maxLines="2"' and 'android:ellipsize="end"' should solve this.

**Comment by vycius** [comment]
@Dekedro Make pull request mentioning this issue with a fix.

**Comment by gediminasel** [comment]
#37 Fixed

**Comment by gediminasel** [comment]
#37
