### ISSUE TITLE
Update Google play screenshots

### ISSUE THREAD

**Issue by vycius** [vycius/NMAkademija#52]
Google play screen shots should be updated.

**Comment by gediminasel** [comment]
![screenshot_1483267258](https://cloud.githubusercontent.com/assets/21194519/21580908/d95bacea-d020-11e6-8837-f121485a1822.png)
![screenshot_1483267070](https://cloud.githubusercontent.com/assets/21194519/21580909/d9783306-d020-11e6-9440-f328a85dd40b.png)
![screenshot_1483267052](https://cloud.githubusercontent.com/assets/21194519/21580910/d9831e42-d020-11e6-85c4-f4ad231650e8.png)
![screenshot_1483267031](https://cloud.githubusercontent.com/assets/21194519/21580911/d98422c4-d020-11e6-8e2b-31d87f3349fd.png)
![screenshot_1483267025](https://cloud.githubusercontent.com/assets/21194519/21580913/d9858db2-d020-11e6-9c4a-2bfacbd05172.png)
![screenshot_1483266998](https://cloud.githubusercontent.com/assets/21194519/21580914/d986a7d8-d020-11e6-817b-11ed5975c94a.png)
![screenshot_1483266965](https://cloud.githubusercontent.com/assets/21194519/21580912/d9848ed0-d020-11e6-946b-f3d5da52ad5b.png)
