### ISSUE TITLE
Redesign downloading offline data screen

### ISSUE THREAD

**Issue by vycius** [vycius/NMAkademija#74]
Currently screen in which offline data is downloaded looks like this:
![screenshot_2017-06-11-18-54-00-340_com nmakademija nmaakademija](https://user-images.githubusercontent.com/3719141/27012411-f10041f4-4ed7-11e7-8fce-1a10e7fbd8c3.png)
It might be one of the first screen user sees. So at least add NMA logo.

**Comment by gediminasel** [comment]
![image](https://user-images.githubusercontent.com/21194519/27013936-2f4b7a28-4ef6-11e7-8afc-fafd2b97b2b1.png)
better?

**Comment by vycius** [comment]
Yup. See PR for comments.
